### ISSUE TITLE
Please use version contstraint in pubspec.yaml

### ISSUE THREAD

**Issue by alfinbi** [TatsuUkraine/dart_environment_config#15]
this package is hard to use while developing angulardart because of conflicting dependency.

as stated in [dart.dev](https://dart.dev/tools/pub/dependencies#version-constraints), **For a library package that you want users to reuse, though, it is important to specify version constraints.**

**Comment by TatsuUkraine** [comment]
Hello. Thank you for this issue. Sorry, but I'm not sure that I'm flowing. Could you explain more what issue is?

**Comment by TatsuUkraine** [comment]
You mean to use `>=...` instead of `^`?

**Comment by TatsuUkraine** [comment]
@alfinbi I figured out what you mean) fix is provided in 2.2.1

**Comment by TatsuUkraine** [comment]
@alfinbi if it's not what you expected, please let me know. https://github.com/TatsuUkraine/dart_environment_config/pull/16/files#diff-fb2d52cd953afedcafc9fe7629c6f132

**Comment by alfinbi** [comment]
Yes, that was what I mean. But I think you should use range from the lowest to the highest. Example :

dart_style: ">=1.0.0 <2.0.0"

Since angular depends on dart_style 1.3.2, your package will never be used as dependency in angulardart app because in your package dart_style starts from 1.3.3.

**Comment by TatsuUkraine** [comment]
@alfinbi second attempt)) now all should be good https://github.com/TatsuUkraine/dart_environment_config/pull/19/files#diff-fb2d52cd953afedcafc9fe7629c6f132R13

**Comment by alfinbi** [comment]
Thanks a lot for your effort. Now I can use your package in my angulardart project.
