### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by Auuufff** [TatsuUkraine/dart_environment_config#30]
Hello. Have a conflict with build_runner 1.10.6

So, because project depends on both environment_config ^2.2.4 and build_runner ^1.10.6, version solving failed.)

**Comment by TatsuUkraine** [comment]
Hi. Hm, this package doesn't have build runner deps. Maybe you have conflict in other dependency?

**Comment by alfinbi** [comment]
dart_style should be using latest version to solve the dependencies conflict. Please update dart_style to higher version or change the dependencies constraint

**Comment by TatsuUkraine** [comment]
@alfinbi @Auuufff new version is available in pub.dev, let me know if it works fine or if you get a problem similar to this one #26 , since dart_style max version was originally limited because of this issue

**Comment by CoMatu** [comment]
```
Because background depends on pigeon ^24.2.1 which depends on dart_style ^3.0.0, dart_style ^3.0.0 is required.
And because environment_config 3.2.0 depends on dart_style ^2.0.0, environment_config 3.2.0 is forbidden.
So, because no versions of environment_config match >3.2.0 <4.0.0 and rms_mobile_v2 depends on environment_config ^3.2.0, version solving failed.
Failed to update packages.
```

**Comment by TatsuUkraine** [comment]
@CoMatu might be you have the same issue as this user https://github.com/TatsuUkraine/dart_environment_config/issues/52
Will try to address it ASAP
