### ISSUE TITLE
yaml dependency with flutter 2.0.4

### ISSUE THREAD

**Issue by danielle-carr** [TatsuUkraine/dart_environment_config#34]
Flutter has now marked version 2.0.4 as stable https://flutter.dev/docs/development/tools/sdk/releases

in my pubspec.yaml the below two dependencies are included
environment_config: ^2.2.5
flutter_launcher_icons: ^0.9.0

When i execute flutter pub get I am getting the below error when using flutter 2.0.4

Because environment_config >=2.2.2 depends on yaml ^2.0.0 and flutter_launcher_icons >=0.9.0 depends on yaml ^3.0.0-nullsafety.0, environment_config >=2.2.2 is incompatible with flutter_launcher_icons >=0.9.0.
So, because myapp depends on both environment_config ^2.2.5 and flutter_launcher_icons ^0.9.0, version solving failed.

Are there any plans to update yaml dependency?

**Comment by TatsuUkraine** [comment]
hi. Yes for sure, I was waiting for all deps been migrated to null-safety (#29) . In your particular case deps conflict happens because of launcher icons package. I can try to update deps, but for now I'm not sure if it possible, meanwhile you can try to use `dependency_overrides` in a deps config to force `yaml` deps to some particular version.

**Comment by TatsuUkraine** [comment]
@danielle-carr new version is available on pub.dev, feel free to reopen this issue if you get any additional deps conflicts after update

**Comment by mlagast** [comment]
Hi @TatsuUkraine, thanks a lot for this new version. 
When I run this command "dart pub outdated --mode=null-safety", the lib is still marked as not compatible for null safety

**Comment by TatsuUkraine** [comment]
@mlagast it won't be null safety compatible because it uses deps that still not migrated (#29 ) at this point I updated deps that was causing conflicts. Unfortunately can't migrate this project untill code_builder is migrated to null, unless you have any workarounds for this

**Comment by TatsuUkraine** [comment]
Oh, nvm) it seems code_build rolled out null safe version 🔥

**Comment by TatsuUkraine** [comment]
@mlagast package is migrated to null-safe, a new version should be available on pub.dev

**Comment by mlagast** [comment]
thanks a lot @TatsuUkraine
