### ISSUE TITLE
Error on Flutter 2.2.0

### ISSUE THREAD

**Issue by Bilonik** [TatsuUkraine/dart_environment_config#39]
Failed to precompile environment_config:generate:
/root/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:1600:40: Error: Getter not found: 'topLevelVariable'.
      return kinds.contains(TargetKind.topLevelVariable);
                                       ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Getter not found: 'topLevelVariable'.
      case TargetKind.topLevelVariable:
                      ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2024:23: Error: Type 'dynamic' of the case expression is not a subtype of type 'TargetKind' of this switch expression.
 - 'TargetKind' is from 'package:meta/meta_meta.dart' ('/root/.pub-cache/hosted/pub.dartlang.org/meta-1.3.0/lib/meta_meta.dart').
      case TargetKind.topLevelVariable:
                      ^
/root/.pub-cache/hosted/pub.dartlang.org/analyzer-1.6.0/lib/src/error/best_practices_verifier.dart:2001:13: Context: The switch expression is here.
    switch (this) {
            ^
pub finished with exit code 1

**Comment by TatsuUkraine** [comment]
It seems it's not related to this package. Looks like analyzer 1.6.0 had a bad release https://github.com/dart-lang/sdk/issues/46136 probably try to update deps and see if issue goes away

**Comment by Bilonik** [comment]
hi @TatsuUkraine , had to declare older version of analyzer for it to work.
analyzer: 1.5.0 , 1.6 breaks this package.

Thank you for this great package

**Comment by TatsuUkraine** [comment]
Thanks) @Bilonik it seems they published 1.7.0 that should fix this problem

**Comment by TatsuUkraine** [comment]
Going to close this issue, since it seems it's not related to this package, but feel free to reopen if issue still remains
