### ISSUE TITLE
Output path

### ISSUE THREAD

**Issue by brenoasm** [TatsuUkraine/dart_environment_config#44]
Hi! This is more like a question, is possible to have an output path param? I need to normalize the param for windows, but passing from the file is not that easy. Is it possible?

**Comment by TatsuUkraine** [comment]
Hi. Could you explain more, what kind of output path? Currently you can specify path for .env and dart file. Or you referring to something else?

**Comment by brenoasm** [comment]
I'm saying if we could specify the output paths from a command, without the filé.

**Comment by TatsuUkraine** [comment]
Sorry, wanted to reply but didn't send the question ((( could you explain what it's not easy to specify path in yaml file? Maybe it's something I need to fix in the package for windows env?
